version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    container_name: frontend
    image: frontend

    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  authentication:
    build: ./distributed-backend/authentication
    container_name: authentication
    image: authentication
    ports:
      - '5050:5050'
    volumes:
      - ./distributed-backend/authentication:/linkedin/authentication
      - ./linkedin/authentication/node_modules
  
  notifications:
    build: ./distributed-backend/notifications
    container_name: notifications
    image: notifications
    ports:
      - '5052:5052'
    volumes:
      - ./distributed-backend/notifications:/linkedin/notifications
      - ./linkedin/notifications/node_modules

  posts:
    build: ./distributed-backend/posts
    container_name: posts
    image: posts

    ports:
      - '5051:5051'
    volumes:
      - ./distributed-backend/posts:/linkedin/posts
      - ./linkedin/posts/node_modules

  user_db:
    image: mongo:latest
    container_name: user_db
    restart: unless-stopped
    volumes:
      - user_data:/data/db

  post_db:
    image: mongo:latest
    container_name: post_db
    restart: unless-stopped
    volumes:
      - post_data:/data/db
  
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090 
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

    command: server /data --console-address ":9090"

    volumes:
      - ~/minio/data:/data

  notification_db:
    image: mongo:latest
    container_name: notification_db
    restart: unless-stopped
    volumes:
      - notification_data:/data/db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  user_data:
  post_data:
  notification_data: